[ req ]
default_bits = 2048
prompt = no
default_md = sha256
distinguished_name = dn
req_extensions = req_ext

[ dn ]
C = KR
ST = Kivotos
L = Millennium Science School
O = Game Development Department
OU = Tendou Aris
CN = *.trycloudflare.com

[ req_ext ]
subjectAltName = @alt_names
basicConstraints = CA:FALSE
keyUsage = digitalSignature, keyEncipherment

[ alt_names ]
DNS.1 = localhost
DNS.2 = *.trycloudflare.com
IP.1 = 172.30.1.98
IP.2 = 172.30.1.99
IP.3 = 172.30.1.100
IP.4 = 172.30.1.97
IP.5 = 172.30.1.96
IP.6 = 172.30.1.95
